### ISSUE TITLE
建议修改获取临时文件夹的方式

### ISSUE THREAD

**Issue by iomect** [tekintian/phpqrcode#1]
$_tmp_dir = $_SERVER['TMPDIR'] ?? $_SERVER['TEMP']; //临时文件目录
建议修改为
$_tmp_dir = sys_get_temp_dir(); //临时文件目录

一套程序迁移到新服务器新系统上发现$_SERVER变量中没有临时文件夹变量

**Comment by tekintian** [comment]
感谢你的反馈,这个问题我们已经看到并修复了, 更新到 v1.1.0版本 即可
